export interface Font {
  url: string;
  name: string;
}

export type FilterText = Record<string, string | undefined>
export interface Templete {
  version: '1';
  w: number;
  h: number;
  layers: Layer[];
  backgroundColor?: string;
  layerColor?: string; // use layers.id 
}

// TODO: add rotation
export type Layer = ShapeLayer | TextLayer;

export interface ShapeLayer {
  id: string; // unique identifier for the layer, used for referencing in filters and colors
  type: 'shape';
  x: number;
  y: number;
  w: number;
  h: number;
  color: string; // 'auto' | '#000000' | 'rgba(0, 0, 0, 1)' | 'hsl(0, 0%, 0%)' - 'auto' use the color generated by the layerColor in the template, if layerColor is not provided, use the color of the previous layer, if the first layer is 'auto', use black as default color.
  image?: string; // URL of the image to be drawn, if provided, the shape will be drawn as an image, otherwise, it will be drawn as a rectangle
  scale?: number; // scale of the image, default is 1, only works when image is provided
  objectFit?: 'cover' | 'contain' | 'fill'; // fit mode for the image within the shape layer
  rotation?: number; // rotation angle in degrees
  svg?: string; // svg string for clipping, if provided, the shape will be clipped by the svg path, and the align property will be used to align the svg path with the shape
  align?: `${'top' | 'bottom' | 'center'} ${'left' | 'right' | 'center'}`
  filter?: Filter; // filter to be applied to the shape, e.g. blur, brightness, contrast, etc.
}

export interface TextLayer {
  id: string;
  type: 'text';
  text: string;
  x: number;
  y: number;
  color: string; // 'auto' | '#000000' | 'rgba(0, 0, 0, 1)' | 'hsl(0, 0%, 0%)' - 'auto' use the color generated by the layerColor in the template, if layerColor is not provided, use the color of the previous layer, if the first layer is 'auto', use black as default color.
  maxWidth?: number; // maximum width for text wrapping
  lineHeight?: number; // line height in pixels for multiline text
  rotation?: number; // rotation angle in degrees
  fontSize?: number; // in pixels
  fontFamily?: string; // e.g. 'Arial', 'Helvetica', 'Times New Roman', etc. If the font is not a system font, it should be provided in the template's fonts property and loaded before drawing the canvas.
  fontWeight?: string; // e.g. 'normal', 'bold', 'bolder', 'lighter', or a number between 100 and 900 if the Font is supported
  strokeColor?: string; // color of text outline/stroke
  strokeWidth?: number; // width of text outline/stroke
  textAlign?: 'left' | 'right' | 'center' | 'start' | 'end'; // default is 'start'
  textBaseline?: 'top' | 'hanging' | 'middle' | 'alphabetic' | 'ideographic' | 'bottom'; // default is 'alphabetic'
  filter?: Filter; // filter to be applied to the text, e.g. blur, brightness, contrast, etc.
}

export interface Filter {
  blur?: string; // e.g. '5px'
  brightness?: string; // e.g. '150%' | '1.5'
  contrast?: string; // e.g. '200%' | '2'
  grayscale?: string; // e.g. '100%' | '1'
  'hue-rotate'?: string; // e.g. '90deg'
  invert?: string; // e.g. '100%' | '1'
  opacity?: string; // e.g. '50%' | '0.5'
  saturate?: string; // e.g. '200%' | '2'
  'drop-shadow'?: string; // e.g. '10px 10px 5px rgba(0,0,0,0.5)'
  sepia?: string; // e.g. '100%' | '1'
}